services:
  ors-app:
    build:
      context: ./
    container_name: matrix-app
    environment:
      - REBUILD_GRAPHS=True
    ports:
      - "8180:8082" # Expose the ORS API on port 8080
      - "9001:9001" # Expose additional port for monitoring (optional)
    volumes:
      - graph-volume:/app/graphs

volumes:
  graph-volume:
