services:
  ors-app:
    build:
      context: ./
    container_name: matrix-app
    ports:
      - "8180:8082" # Expose the ORS API on port 8080
      - "9001:9001" # Expose additional port for monitoring (optional)
