services:
  ors-app-sydney:
    build:
      context: ./
    environment:
      - REBUILD_GRAPHS=True
    container_name: matrix-app-sydney
    ports:
      - "127.0.0.1:8280:8082" # Expose the ORS API on port 8080
      - "127.0.0.1:9201:9001" # Expose additional port for monitoring (optional)

    volumes:
      - graph-sydney-volume:/app/graphs

volumes:
  graph-sydney-volume:
