ors:
  engine:
    threads: 2 # match with 2 CPU

    elevation:
      enabled: false # disable for performance still now working

    profile_default:
      build:
        source_file: data.osm.pbf

    profiles:
      driving-car:
        enabled: true
        preparation:
          methods:
            ch:
              enabled: true # MUST for matrix performance

      foot-walking:
        enabled: false
        preparation:
          methods:
            ch:
              enabled: true # MUST for matrix performance

  endpoints:
    matrix:
      enabled: true

      #VERY IMPORTANT LIMITS (protect VPS)
      maximum_routes: 10000
      maximum_routes_flexible: 500

      # prevent huge graph exploration
      maximum_visited_nodes: 1000000

      # radius (reduce if possible)
      maximum_search_radius: 3000

      allow_resolve_locations: false # faster (skip reverse lookup)
